### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by fpg1503** [jamis/MazeMaker#2]
Hey there! I really enjoyed this repo and it came in extremely hand this weekend during GGJ.

What's the license so I can license [the game my team made](https://github.com/fpg1503/ComeHome) accordingly?

Thanks for this awesome contribution to OSS! 👍

**Comment by jamis** [comment]
Thanks! I'm glad it was helpful!

I don't have time just now to put up a proper license file, but you may assume it is licensed under the MIT license (per https://opensource.org/licenses/MIT). I'll update the repo as soon as I can.
